name: Build Elite Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev flex bison clang lld llvm

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Elite"
          export KBUILD_BUILD_HOST="Spes-Lab"

          # КОРРЕКЦИЯ GPU: Выставляем 1175 МГц перед сборкой
          # Мы ищем файл dtsi для графики и меняем максимальный уровень на 1175000000 Гц
          find arch/arm64/boot/dts/vendor/qcom/ -name "*gpu*.dtsi" -exec sed -i 's/qcom,gpu-pwrlevel-bin = <0>/qcom,gpu-pwrlevel-bin = <1175000000>/g' {} +
          find arch/arm64/boot/dts/vendor/qcom/ -name "*gpu*.dtsi" -exec sed -i 's/opp-hz = \/bits\/ 64 <[0-9]*>/opp-hz = \/bits\/ 64 <1175000000>/' {} +

          # Очистка и конфигурация
          make clean
          make mrproper
          make vendor/spes_defconfig
          
          # Сама сборка
          make -j2 -k \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                      CONFIG_SECTION_MISMATCH_WARN_ONLY=y \
                      KCFLAGS="-w" \
                      HOSTCFLAGS="-w" || true

      - name: Check and Package
        run: |
          # Создаем папку для артефактов
          mkdir -p final_bin
          
          # Копируем всё, что удалось собрать (Image и Image.gz)
          cp arch/arm64/boot/Image* final_bin/
          
          if [ -n "$(ls -A final_bin/)" ]; then
            echo "SUCCESS: Kernel files found!"
            ls -l final_bin/
          else
            echo "ERROR: No kernel files found at all."
            exit 1
          fi

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Image-Elite-Spes
          # Загружаем всю папку со всеми версиями ядра
          path: final_bin/*
