name: Build Elite Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libncurses5-dev flex bison clang lld llvm

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Elite"
          export KBUILD_BUILD_HOST="Spes-Lab"
          
          # Очистка и создание конфига
          make clean
          make mrproper
          make vendor/spes_defconfig
          
          # Запуск сборки без внешней папки (так надежнее)
          make -j2 -k \
                      ARCH=arm64 \
                      CC=clang \
                      CLANG_TRIPLE=aarch64-linux-gnu- \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                      CONFIG_SECTION_MISMATCH_WARN_ONLY=y \
                      KCFLAGS="-w" \
                      HOSTCFLAGS="-w" || true

      - name: Check and Package
        run: |
          # Ищем готовое ядро
          if [ -f arch/arm64/boot/Image.gz-dtb ]; then
            echo "SUCCESS: Image.gz-dtb found!"
          else
            echo "ERROR: Kernel image not found. Showing what was built:"
            find arch/arm64/boot/ -name "Image*"
            exit 1
          fi

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Image-Elite-Spes
          path: arch/arm64/boot/Image.gz-dtb
