name: Build Elite Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clang
        run: |
          mkdir -p clang
          cd clang
          # Качаем проверенный Proton Clang - он лучше всего подходит для ядер Xiaomi
          git clone https://github.com/kdrag0n/proton-clang.git --depth=1 bin
          
      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/bin/bin:$PATH
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Elite"
          export KBUILD_BUILD_HOST="Spes-Lab"
          
          # Указываем путь к компилятору явно
          CLANG=$(pwd)/clang/bin/bin/clang
          
          make O=out ARCH=arm64 vendor/spes_defconfig
          
          make -j$(nproc --all) O=out \
                      ARCH=arm64 \
                      CC=$CLANG \
                      CROSS_COMPILE=aarch64-linux-gnu- \
                      CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
                      AR=llvm-ar \
                      NM=llvm-nm \
                      OBJCOPY=llvm-objcopy \
                      OBJDUMP=llvm-objdump \
                      STRIP=llvm-strip \
                      LD=ld.lld \
                      LLVM=1 \
                      LLVM_IAS=1 \
                      KCFLAGS="-w"
                      

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Image-Elite-Spes
          path: out/arch/arm64/boot/Image.gz-dtb
          
